

services:
  web:
    build: .
    ports:
      - "5010:5010"
    env_file:
      - .env
    volumes:
      - ./instance:/app/instance
    restart: unless-stopped
    environment:
      - FLASK_ENV=production
